import './globals.css';
import { Outfit } from 'next/font/google';
import AOSAnimation from './utils/AosInit';

const outfit = Outfit({ subsets: ['latin'] });

export const metadata = {
  title: 'Destiny Travels and Tours',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={outfit.className}>
        <AOSAnimation>{children}</AOSAnimation>
      </body>
    </html>
  );
}
